"""
Generate professional prescription forms based on scan analysis.
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle


def generate_diagnosis_summary(analysis_data: dict) -> str:
    """Create a brief clinical diagnosis summary from analysis."""
    has_tumor = analysis_data.get("has_tumor", False)
    tumor_type = analysis_data.get("tumor_type", "Not Available")
    size = analysis_data.get("size", "Not Available")
    location = analysis_data.get("location", "Not Available")
    confidence = analysis_data.get("confidence", 0)

    if isinstance(confidence, (int, float)):
        confidence_pct = f"{round(confidence * 100, 1)}%"
    else:
        confidence_pct = "Not Available"

    if has_tumor:
        return (
            f"Brain scan reveals a suspected {tumor_type} ({size}) in the {location} "
            f"with {confidence_pct} confidence. Immediate clinical correlation recommended."
        )
    else:
        return (
            f"Brain scan analysis shows no significant abnormalities detected. "
            f"Continue routine follow-up as clinically indicated."
        )


def generate_recommendations(analysis_data: dict) -> list:
    """Generate recommended next steps based on analysis."""
    has_tumor = analysis_data.get("has_tumor", False)
    tumor_type = analysis_data.get("tumor_type", "").lower()

    recommendations = []

    if has_tumor:
        recommendations.append("• Refer to Neurosurgery for consultation")
        if "glioma" in tumor_type:
            recommendations.append("• MRI with contrast enhancement for staging")
            recommendations.append("• Consider biopsy for tissue confirmation")
        else:
            recommendations.append("• Advanced imaging (CT/MRI) for characterization")
        recommendations.append("• Neurology assessment for seizure prophylaxis if indicated")
        recommendations.append("• Regular follow-up imaging every 3 months")
    else:
        recommendations.append("• Continue routine clinical observation")
        recommendations.append("• Annual neuroimaging follow-up")
        recommendations.append("• Advise patient on symptoms requiring urgent evaluation")

    return recommendations


def generate_prescription(analysis_data: dict, patient_id: str = "Not Available", out_dir: str = ".") -> str:
    """
    Generate a professional prescription/recommendation form PDF.
    
    Args:
        analysis_data: The scan analysis dict
        patient_id: Patient ID or report ID
        out_dir: Output directory for the PDF
    
    Returns:
        Absolute path to the generated PDF
    """
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    human_dt = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    filename = f"prescription_{timestamp_str}.pdf"
    filepath = os.path.join(out_dir, filename)

    doc = SimpleDocTemplate(
        filepath,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=72,
    )
    styles = getSampleStyleSheet()
    normal = styles["Normal"]

    elems = []

    # Header
    elems.append(
        Paragraph(
            "AI-Assisted Prescription & Recommendation Form",
            ParagraphStyle(name="Title", fontSize=16, leading=20, alignment=1),
        )
    )
    elems.append(Spacer(1, 12))

    # Metadata
    meta_data = [
        ["Patient/Report ID:", patient_id],
        ["Date & Time:", human_dt],
        ["Generated by:", "AI Medical Assistant"],
    ]
    meta_table = Table(meta_data, colWidths=[2.0 * inch, 4.0 * inch])
    meta_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TEXTCOLOR", (0, 0), (0, -1), colors.darkblue),
            ]
        )
    )
    elems.append(meta_table)
    elems.append(Spacer(1, 18))

    # Diagnosis Section
    elems.append(Paragraph("Diagnosis Summary", styles["Heading2"]))
    elems.append(Spacer(1, 6))
    diagnosis = generate_diagnosis_summary(analysis_data)
    elems.append(Paragraph(diagnosis, normal))
    elems.append(Spacer(1, 12))

    # Recommendations Section
    elems.append(Paragraph("Recommended Next Steps", styles["Heading2"]))
    elems.append(Spacer(1, 6))
    recommendations = generate_recommendations(analysis_data)
    for rec in recommendations:
        elems.append(Paragraph(rec, normal))
    elems.append(Spacer(1, 12))

    # Doctor Signature Section
    elems.append(Paragraph("Doctor Certification", styles["Heading2"]))
    elems.append(Spacer(1, 6))

    sig_table_data = [
        ["Doctor Name (Print):", "_" * 40],
        ["Doctor Signature:", "_" * 40],
        ["License Number:", "_" * 40],
        ["Date:", "_" * 40],
    ]
    sig_table = Table(sig_table_data, colWidths=[2.0 * inch, 4.0 * inch])
    sig_table.setStyle(
        TableStyle(
            [
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
            ]
        )
    )
    elems.append(sig_table)
    elems.append(Spacer(1, 24))

    # Footer
    footer = Paragraph(
        "<i>Note: This prescription form is AI-generated and requires physician review and signature before clinical use. "
        "Please consult a specialist for further analysis. This form was securely generated after QR verification.</i>",
        ParagraphStyle(name="Footer", fontSize=8, alignment=1, textColor=colors.grey),
    )
    elems.append(footer)

    # Build PDF
    doc.build(elems)

    return os.path.abspath(filepath)


if __name__ == "__main__":
    # Example usage
    example_json = {
        "has_tumor": True,
        "tumor_type": "Glioma",
        "size": "1.2 cm",
        "location": "Right occipital lobe",
        "confidence": 0.9,
    }

    out_path = generate_prescription(example_json, patient_id="PAT-20251111-001")
    print(out_path)
